require('colors');

console.log("");
console.log("Modulo de edicao remota WEBSTORE".green.bold);
console.log("");
console.log("Para saber mais como utilizar o modulo acesse:");
console.log("https://edittemas.developers.webstore.net.br/");
console.log("");
console.log("Principais comandos:".green.bold);
console.log("");
console.log("node config ".yellow.bold);
console.log("Esse comando inicia o processo de edicao permitindo que voce informe o token do tema e loja que ira personalizar");
console.log("");
console.log("node pull ".yellow.bold);
console.log("Apos realizar a configuracao, voce devera executar o domando de download para baixar o conteudo atual do tema informado");
console.log("");
console.log("node status ".yellow.bold);
console.log("Executando esse comando voce sabera qual loja e tema esta personalizando no momento");
console.log("");
console.log("npm start ".yellow.bold + "(atencao pois e o unico comando que ao inves de node utiliza npm no inicio)");
console.log("Ao executar esse comando, voce podera visualizar o andamento da loja no seu navegador atraves do link http://localhost:3000");
console.log("");
console.log("node setpage ".yellow.bold);
console.log("Utilize esse comando para informar a url da pagina que deseja editar. Por padrao, o tema inicia personalizando a home. Para editar outras paginas e necessario informar a url que sera alterada por esse comando.");
console.log("");
console.log("node mod ".yellow.bold);
console.log("Utilize esse comando para criar modulos personalizados para o tema.");
console.log("");
console.log("node push ".yellow.bold);
console.log("Apos finalizar a edicao do tema, voce devera fazer o deploy do mesmo com o comando de upload para subir a edicao para a loja");
console.log("");
console.log("node backup ".yellow.bold);
console.log("Cria backups do conteudo atual da personalizacao que podem ser restaurados posteriormente com o comando node restore");
console.log("");
console.log("node restore ".yellow.bold);
console.log("Rastaura na pasta layout um backup criado anteriormente com o comando node backup");
console.log("");
console.log("node pref ".yellow.bold);
console.log("Cria e gerencia prefer�ncias do layout, como cores e op��es a serem escolhidas no painel pelo lojista.");
console.log("");
console.log("");
console.log("Em caso de duvidas, conte com nosso time de especialistas atraves do email abaixo.");
console.log("developers@webstore.com.br");
console.log("");
console.log("=)".green.bold);
console.log("");
